github.com:
    users:
        LunarStorm97:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: LunarStorm97
